name: Request Pull Request

on:
  push:
    branches:
      - main

jobs:
  request-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Clone service-catalog repository
      uses: actions/checkout@v2
      with:
        repository: centralcordoba/githubworkflowB
        token: ${{ secrets.GITHUB_TOKEN }}
        path: temp-repo

    - name: Copy swagger.yaml to repository service-catalog
      run: |
        cp swagger.yaml temp-repo/swagger.yaml

    - name: Create Pull Request in service-catalog repository
      uses: centralcordoba/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: temp-repo
        commit-message: Update swagger.yaml
        title: Update swagger.yaml
        body: Updated file swagger.yaml from incidents repository.
        branch: update-swagger
        base: main
        reviewers: centralcordoba